email:
  subject: "SDRM Reservation confirmation"
  text: "Your reservation has been proceed correctly, enjoy your time!"

server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  banner:
    location: classpath:banner.txt
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdrmapp@gmail.com
    password: Sdrmadmin1!
    properties:
      "mail.smtp.starttls.enable": true
    test-connection: false
management:
  health:
    mail:
      enabled: false
jwt:
  expirationTime: 3600000
  secret: secretForEncodingSignature


logging:
  level:
    org:
      springframework:
        security: DEBUG
#  security:
#    user:
#      name: user
#      password: user
